name: Update Dependencies

on:
  schedule:
  - cron: 0 0 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install -g npm-check-updates

    - name: Update packages
      id: update
      run: |
        report="$(ncu -u)"
        report="\`\`\`
        ${report}
        \`\`\`"
        report="${report//'%'/'%25'}"
        report="${report//$'\n'/'%0A'}"
        report="${report//$'\r'/'%0D'}"
        echo "::set-output name=ncu::${report}"

    - run: npm update --save-dev

    - run: npm update

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        commit-message: "Update dependencies"
        title: "Update dependencies"
        body: ${{ steps.update.outputs.ncu }}
        branch: feature/update-dependencies
        token: ${{ secrets.PR_CREATE_TOKEN }}
        labels: dependencies
